version: '3'
services:
  nginx:
    build: ./images/nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/mysyte.com.conf:/etc/nginx/conf.d/mysyte.com.conf
      - ./src:/var/www
    environment:
      - MY_VAR=value
    depends_on:
      - php
  php:
    build: ./images/php
    volumes:
      - ./src:/var/www
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - /etc/mysql:/etc/mysql
      - ./mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 6a12
      MYSQL_DATABASE: blog
