server {
  listen 80;
  server_name mysyte.com
  index index.php;
  root /var/www;

  location /assets/ {
    root /var/www;
    access_log off;
    expires 30d;
    add_header Cache-Control "public";
  }

  location ~ (\.php|/)$ {
    include /etc/nginx/fastcgi_params;
    fastcgi_pass php:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }

  location ~ \.cgi$ {
    include /etc/nginx/fastcgi_params;
    fastcgi_pass unix:/var/run/fcgiwrap.socket;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }

  location ~* ^.+\.(png|jpeg|ico|jpg|gif|svg|css|js)$ {
    expires 30d;
    add_header Cache-Control "public, no-transform";
    tcp_nodelay       off;
    open_file_cache          max=1000 inactive=20s;
    open_file_cache_valid    30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors   on;
    add_header X-Content-Type-Options "nosniff";
  }

  location / {
    try_files $uri $uri/ =404;
  }
}